
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-11T09:15:20-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "2d3443d3f5b660ca005831654d7a2ddb526cd8e3",
 "version": "0.4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
