# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'ResourceLimits',
]

@pulumi.output_type
class ResourceLimits(dict):
    def __init__(__self__, *,
                 external_network_quota: float,
                 memory_quota: float,
                 public_ip_quota: float,
                 vcpu_quota: float,
                 vdisk_space_quota: float):
        pulumi.set(__self__, "external_network_quota", external_network_quota)
        pulumi.set(__self__, "memory_quota", memory_quota)
        pulumi.set(__self__, "public_ip_quota", public_ip_quota)
        pulumi.set(__self__, "vcpu_quota", vcpu_quota)
        pulumi.set(__self__, "vdisk_space_quota", vdisk_space_quota)

    @property
    @pulumi.getter
    def external_network_quota(self) -> float:
        return pulumi.get(self, "external_network_quota")

    @property
    @pulumi.getter
    def memory_quota(self) -> float:
        return pulumi.get(self, "memory_quota")

    @property
    @pulumi.getter
    def public_ip_quota(self) -> float:
        return pulumi.get(self, "public_ip_quota")

    @property
    @pulumi.getter
    def vcpu_quota(self) -> float:
        return pulumi.get(self, "vcpu_quota")

    @property
    @pulumi.getter
    def vdisk_space_quota(self) -> float:
        return pulumi.get(self, "vdisk_space_quota")


