# coding: utf-8

"""
    Data Repository API

    <details><summary>This document defines the REST API for the Terra Data Repository.</summary> <p> **Status: design in progress** There are a few top-level endpoints (besides some used by swagger):  * / - generated by swagger: swagger API page that provides this documentation and a live UI for submitting REST requests  * /status - provides the operational status of the service  * /configuration - provides the basic configuration and information about the service  * /api - is the authenticated and authorized Data Repository API  * /ga4gh/drs/v1 - is a transcription of the Data Repository Service API  The API endpoints are organized by interface. Each interface is separately versioned. <p> **Notes on Naming** <p> All of the reference items are suffixed with \\\"Model\\\". Those names are used as the class names in the generated Java code. It is helpful to distinguish these model classes from other related classes, like the DAO classes and the operation classes. </details>   # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from data_repo_client import schemas  # noqa: F401


class IamResourceTypeEnum(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    The type of journal entries to return.  DATASET maps to Dataset, DATASNAPSHOT maps to Snapshot, SPEND_PROFILE maps to Profile.  DATAREPO and WORKSPACE are not implemented at this time but are included in the list for completeness.

    """


    class MetaOapg:
        enum_value_to_name = {
            "DATASET": "DATASET",
            "DATASNAPSHOT": "DATASNAPSHOT",
            "SPEND_PROFILE": "SPEND_PROFILE",
            "DATAREPO": "DATAREPO",
            "WORKSPACE": "WORKSPACE",
        }
    
    @schemas.classproperty
    def DATASET(cls):
        return cls("DATASET")
    
    @schemas.classproperty
    def DATASNAPSHOT(cls):
        return cls("DATASNAPSHOT")
    
    @schemas.classproperty
    def SPEND_PROFILE(cls):
        return cls("SPEND_PROFILE")
    
    @schemas.classproperty
    def DATAREPO(cls):
        return cls("DATAREPO")
    
    @schemas.classproperty
    def WORKSPACE(cls):
        return cls("WORKSPACE")
