# coding: utf-8

"""
    Data Repository API

    <details><summary>This document defines the REST API for the Terra Data Repository.</summary> <p> **Status: design in progress** There are a few top-level endpoints (besides some used by swagger):  * / - generated by swagger: swagger API page that provides this documentation and a live UI for submitting REST requests  * /status - provides the operational status of the service  * /configuration - provides the basic configuration and information about the service  * /api - is the authenticated and authorized Data Repository API  * /ga4gh/drs/v1 - is a transcription of the Data Repository Service API  The API endpoints are organized by interface. Each interface is separately versioned. <p> **Notes on Naming** <p> All of the reference items are suffixed with \\\"Model\\\". Those names are used as the class names in the generated Java code. It is helpful to distinguish these model classes from other related classes, like the DAO classes and the operation classes. </details>   # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from data_repo_client.paths.ga4gh_drs_v1_objects_object_id_access_access_id.get import GetAccessUrl
from data_repo_client.paths.ga4gh_drs_v1_objects_object_id.get import GetObject
from data_repo_client.paths.ga4gh_drs_v1_service_info.get import GetServiceInfo
from data_repo_client.paths.ga4gh_drs_v1_objects_object_id.options import OptionsObject
from data_repo_client.paths.ga4gh_drs_v1_objects_object_id_access_access_id.post import PostAccessUrl
from data_repo_client.paths.ga4gh_drs_v1_objects_object_id.post import PostObject


class DataRepositoryServiceApi(
    GetAccessUrl,
    GetObject,
    GetServiceInfo,
    OptionsObject,
    PostAccessUrl,
    PostObject,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
