# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strmprivacy/api/paging/v1/paging_v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)strmprivacy/api/paging/v1/paging_v1.proto\x12\x19strmprivacy.api.paging.v1\"2\n\x12TimestampPageToken\x12\x1c\n\ttimestamp\x18\x01 \x01(\tR\ttimestampBc\n\x1cio.strmprivacy.api.paging.v1P\x01ZAgithub.com/strmprivacy/api-definitions-go/v3/api/paging/v1;pagingb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'strmprivacy.api.paging.v1.paging_v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034io.strmprivacy.api.paging.v1P\001ZAgithub.com/strmprivacy/api-definitions-go/v3/api/paging/v1;paging'
  _TIMESTAMPPAGETOKEN._serialized_start=72
  _TIMESTAMPPAGETOKEN._serialized_end=122
# @@protoc_insertion_point(module_scope)
