# coding: utf-8

"""
    Flywheel

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


## NOTE: This file is auto generated by the swagger code generator program.
## Do not edit the file manually.

import pprint
import re  # noqa: F401
import six

from flywheel.models.project_sharing_settings_project_counters import ProjectSharingSettingsProjectCounters  # noqa: F401,E501

class ProjectSharingSettingsProjectStats(object):

    swagger_types = {
        'number_of': 'ProjectSharingSettingsProjectCounters',
        'age_groups': 'str',
        'measurements': 'str',
        'modalities': 'str',
        'file_types': 'str'
    }

    attribute_map = {
        'number_of': 'number-of',
        'age_groups': 'age-groups',
        'measurements': 'measurements',
        'modalities': 'modalities',
        'file_types': 'file-types'
    }

    rattribute_map = {
        'number-of': 'number_of',
        'age-groups': 'age_groups',
        'measurements': 'measurements',
        'modalities': 'modalities',
        'file-types': 'file_types'
    }

    def __init__(self, number_of=None, age_groups=None, measurements=None, modalities=None, file_types=None):  # noqa: E501
        """ProjectSharingSettingsProjectStats - a model defined in Swagger"""
        super(ProjectSharingSettingsProjectStats, self).__init__()

        self._number_of = None
        self._age_groups = None
        self._measurements = None
        self._modalities = None
        self._file_types = None
        self.discriminator = None
        self.alt_discriminator = None

        if number_of is not None:
            self.number_of = number_of
        if age_groups is not None:
            self.age_groups = age_groups
        if measurements is not None:
            self.measurements = measurements
        if modalities is not None:
            self.modalities = modalities
        if file_types is not None:
            self.file_types = file_types

    @property
    def number_of(self):
        """Gets the number_of of this ProjectSharingSettingsProjectStats.


        :return: The number_of of this ProjectSharingSettingsProjectStats.
        :rtype: ProjectSharingSettingsProjectCounters
        """
        return self._number_of

    @number_of.setter
    def number_of(self, number_of):
        """Sets the number_of of this ProjectSharingSettingsProjectStats.


        :param number_of: The number_of of this ProjectSharingSettingsProjectStats.  # noqa: E501
        :type: ProjectSharingSettingsProjectCounters
        """

        self._number_of = number_of

    @property
    def age_groups(self):
        """Gets the age_groups of this ProjectSharingSettingsProjectStats.


        :return: The age_groups of this ProjectSharingSettingsProjectStats.
        :rtype: str
        """
        return self._age_groups

    @age_groups.setter
    def age_groups(self, age_groups):
        """Sets the age_groups of this ProjectSharingSettingsProjectStats.


        :param age_groups: The age_groups of this ProjectSharingSettingsProjectStats.  # noqa: E501
        :type: str
        """

        self._age_groups = age_groups

    @property
    def measurements(self):
        """Gets the measurements of this ProjectSharingSettingsProjectStats.


        :return: The measurements of this ProjectSharingSettingsProjectStats.
        :rtype: str
        """
        return self._measurements

    @measurements.setter
    def measurements(self, measurements):
        """Sets the measurements of this ProjectSharingSettingsProjectStats.


        :param measurements: The measurements of this ProjectSharingSettingsProjectStats.  # noqa: E501
        :type: str
        """

        self._measurements = measurements

    @property
    def modalities(self):
        """Gets the modalities of this ProjectSharingSettingsProjectStats.


        :return: The modalities of this ProjectSharingSettingsProjectStats.
        :rtype: str
        """
        return self._modalities

    @modalities.setter
    def modalities(self, modalities):
        """Sets the modalities of this ProjectSharingSettingsProjectStats.


        :param modalities: The modalities of this ProjectSharingSettingsProjectStats.  # noqa: E501
        :type: str
        """

        self._modalities = modalities

    @property
    def file_types(self):
        """Gets the file_types of this ProjectSharingSettingsProjectStats.


        :return: The file_types of this ProjectSharingSettingsProjectStats.
        :rtype: str
        """
        return self._file_types

    @file_types.setter
    def file_types(self, file_types):
        """Sets the file_types of this ProjectSharingSettingsProjectStats.


        :param file_types: The file_types of this ProjectSharingSettingsProjectStats.  # noqa: E501
        :type: str
        """

        self._file_types = file_types


    @staticmethod
    def positional_to_model(value):
        """Converts a positional argument to a model value"""
        return value

    def return_value(self):
        """Unwraps return value from model"""
        return self

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectSharingSettingsProjectStats):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other

    # Container emulation
    def __getitem__(self, key):
        """Returns the value of key"""
        key = self._map_key(key)
        return getattr(self, key)

    def __setitem__(self, key, value):
        """Sets the value of key"""
        key = self._map_key(key)
        setattr(self, key, value)

    def __contains__(self, key):
        """Checks if the given value is a key in this object"""
        key = self._map_key(key, raise_on_error=False)
        return key is not None

    def keys(self):
        """Returns the list of json properties in the object"""
        return self.__class__.rattribute_map.keys()

    def values(self):
        """Returns the list of values in the object"""
        for key in self.__class__.attribute_map.keys():
            yield getattr(self, key)

    def items(self):
        """Returns the list of json property to value mapping"""
        for key, prop in self.__class__.rattribute_map.items():
            yield key, getattr(self, prop)

    def get(self, key, default=None):
        """Get the value of the provided json property, or default"""
        key = self._map_key(key, raise_on_error=False)
        if key:
            return getattr(self, key, default)
        return default

    def _map_key(self, key, raise_on_error=True):
        result = self.__class__.rattribute_map.get(key)
        if result is None:
            if raise_on_error:
                raise AttributeError('Invalid attribute name: {}'.format(key))
            return None
        return '_' + result
