from setuptools import setup, find_packages

setup(
    name="Jakit",
    version="0.9",
    packages=find_packages(),
    author="Idriss Animashaun",
    author_email="idriss.animashaun@intel.com",
    description="Just Another Kappa Information Tool",
    long_description=open('README.md').read(),
    long_description_content_type="text/markdown",
    url="https://github.com/iddy-ani/Jakit",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    install_requires=[
        "anyio",
        "bleach",
        "blinker",
        "certifi",
        "charset-normalizer",
        "click",
        "colorama",
        "Dager",
        "dnspython",
        "docutils",
        "exceptiongroup",
        "Flask",
        "h11",
        "httpcore",
        "idna",
        "importlib-metadata",
        "itsdangerous",
        "jaraco.classes",
        "Jinja2",
        "keyring",
        "markdown-it-py",
        "MarkupSafe",
        "mdurl",
        "more-itertools",
        "numpy",
        "pandas",
        "pkginfo",
        "Pygments",
        "pymongo",
        "python-dateutil",
        "pytz",
        "pywin32-ctypes",
        "readme-renderer",
        "requests",
        "requests-toolbelt",
        "rfc3986",
        "rich",
        "six",
        "sniffio",
        "tzdata",
        "urllib3",
        "webencodings",
        "Werkzeug",
        "zipp"
    ],
    python_requires='>=3.10',
)
