
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-11T14:49:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e9923071aaa4bd97b7a2064c6fbb74b311618ccf",
 "version": "0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
