from nwon_baseline.directory_helper.directory_content import directory_paths_in_directory as directory_paths_in_directory, file_paths_in_directory as file_paths_in_directory
from typing import List

def create_paths(paths: List[str]) -> None: ...
def copy_directory(source_directory: str, target_directory: str) -> None: ...
def clean_directory(directory: str, recursive: bool = ...): ...
