
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-12T00:53:38+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "8e31c799efbb977e46fb8b6f8db5188212d40abf",
 "version": "0.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
