
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-09T11:47:50-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9641a51b142a8c18322150b87a837fdf3a865209",
 "version": "1.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
