# coding: utf-8

"""
    RIME Rest API

    API methods for RIME. Must be authenticated with `rime-api-key` header.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: dev@robustintelligence.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TestrunPredInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'connection_info': 'TestrunConnectionInfo',
        'pred_params': 'TestrunPredictionParams'
    }

    attribute_map = {
        'connection_info': 'connectionInfo',
        'pred_params': 'predParams'
    }

    def __init__(self, connection_info=None, pred_params=None):  # noqa: E501
        """TestrunPredInfo - a model defined in Swagger"""  # noqa: E501
        self._connection_info = None
        self._pred_params = None
        self.discriminator = None
        if connection_info is not None:
            self.connection_info = connection_info
        if pred_params is not None:
            self.pred_params = pred_params

    @property
    def connection_info(self):
        """Gets the connection_info of this TestrunPredInfo.  # noqa: E501


        :return: The connection_info of this TestrunPredInfo.  # noqa: E501
        :rtype: TestrunConnectionInfo
        """
        return self._connection_info

    @connection_info.setter
    def connection_info(self, connection_info):
        """Sets the connection_info of this TestrunPredInfo.


        :param connection_info: The connection_info of this TestrunPredInfo.  # noqa: E501
        :type: TestrunConnectionInfo
        """

        self._connection_info = connection_info

    @property
    def pred_params(self):
        """Gets the pred_params of this TestrunPredInfo.  # noqa: E501


        :return: The pred_params of this TestrunPredInfo.  # noqa: E501
        :rtype: TestrunPredictionParams
        """
        return self._pred_params

    @pred_params.setter
    def pred_params(self, pred_params):
        """Sets the pred_params of this TestrunPredInfo.


        :param pred_params: The pred_params of this TestrunPredInfo.  # noqa: E501
        :type: TestrunPredictionParams
        """

        self._pred_params = pred_params

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TestrunPredInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TestrunPredInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
