# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/dbu/v0/dbumodels.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ansys/api/dbu/v0/dbumodels.proto\x12\x10\x61nsys.api.dbu.v0\"\x1e\n\x10\x45ntityIdentifier\x12\n\n\x02id\x18\x01 \x01(\t\"~\n\x10\x44rivingDimension\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x37\n\x0e\x64imension_type\x18\x03 \x01(\x0e\x32\x1f.ansys.api.dbu.v0.DimensionType\x12\x17\n\x0f\x64imension_value\x18\x04 \x01(\x01\"\xde\x01\n\x06\x44\x65sign\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0bis_complete\x18\x02 \x01(\x08\x12\x11\n\tis_locked\x18\x03 \x01(\x08\x12\x13\n\x0bis_modified\x18\x04 \x01(\x08\x12\x12\n\nis_removed\x18\x05 \x01(\x08\x12\x35\n\tmain_part\x18\x06 \x01(\x0b\x32\".ansys.api.dbu.v0.EntityIdentifier\x12$\n\x1cmain_part_displays_file_name\x18\x07 \x01(\x08\x12\x0c\n\x04path\x18\n \x01(\t\x12\x0c\n\x04name\x18\x0b \x01(\t*\xac\x02\n\rDimensionType\x12\x19\n\x15\x44IMENSIONTYPE_UNKNOWN\x10\x00\x12\x18\n\x14\x44IMENSIONTYPE_LINEAR\x10\x01\x12\x1b\n\x17\x44IMENSIONTYPE_DIAMETRIC\x10\x02\x12\x18\n\x14\x44IMENSIONTYPE_RADIAL\x10\x03\x12\x15\n\x11\x44IMENSIONTYPE_ARC\x10\x04\x12\x16\n\x12\x44IMENSIONTYPE_AREA\x10\x05\x12\x18\n\x14\x44IMENSIONTYPE_VOLUME\x10\x06\x12\x16\n\x12\x44IMENSIONTYPE_MASS\x10\x07\x12\x19\n\x15\x44IMENSIONTYPE_ANGULAR\x10\x08\x12\x17\n\x13\x44IMENSIONTYPE_COUNT\x10\t\x12\x1a\n\x16\x44IMENSIONTYPE_UNITLESS\x10\n*8\n\x0bImageFormat\x12\x13\n\x0fIMAGEFORMAT_PNG\x10\x00\x12\x14\n\x10IMAGEFORMAT_JPEG\x10\x01*\xd5\x01\n\nWindowView\x12\x12\n\x0eWINDOWVIEW_TOP\x10\x00\x12\x15\n\x11WINDOWVIEW_BOTTOM\x10\x01\x12\x13\n\x0fWINDOWVIEW_LEFT\x10\x02\x12\x14\n\x10WINDOWVIEW_RIGHT\x10\x03\x12\x14\n\x10WINDOWVIEW_FRONT\x10\x04\x12\x13\n\x0fWINDOWVIEW_BACK\x10\x05\x12\x18\n\x14WINDOWVIEW_ISOMETRIC\x10\x06\x12\x18\n\x14WINDOWVIEW_TRIMETRIC\x10\x07\x12\x12\n\x0eWINDOWVIEW_FIT\x10\x08\x42\x13\xaa\x02\x10\x41nsys.Api.Dbu.V0b\x06proto3')

_DIMENSIONTYPE = DESCRIPTOR.enum_types_by_name['DimensionType']
DimensionType = enum_type_wrapper.EnumTypeWrapper(_DIMENSIONTYPE)
_IMAGEFORMAT = DESCRIPTOR.enum_types_by_name['ImageFormat']
ImageFormat = enum_type_wrapper.EnumTypeWrapper(_IMAGEFORMAT)
_WINDOWVIEW = DESCRIPTOR.enum_types_by_name['WindowView']
WindowView = enum_type_wrapper.EnumTypeWrapper(_WINDOWVIEW)
DIMENSIONTYPE_UNKNOWN = 0
DIMENSIONTYPE_LINEAR = 1
DIMENSIONTYPE_DIAMETRIC = 2
DIMENSIONTYPE_RADIAL = 3
DIMENSIONTYPE_ARC = 4
DIMENSIONTYPE_AREA = 5
DIMENSIONTYPE_VOLUME = 6
DIMENSIONTYPE_MASS = 7
DIMENSIONTYPE_ANGULAR = 8
DIMENSIONTYPE_COUNT = 9
DIMENSIONTYPE_UNITLESS = 10
IMAGEFORMAT_PNG = 0
IMAGEFORMAT_JPEG = 1
WINDOWVIEW_TOP = 0
WINDOWVIEW_BOTTOM = 1
WINDOWVIEW_LEFT = 2
WINDOWVIEW_RIGHT = 3
WINDOWVIEW_FRONT = 4
WINDOWVIEW_BACK = 5
WINDOWVIEW_ISOMETRIC = 6
WINDOWVIEW_TRIMETRIC = 7
WINDOWVIEW_FIT = 8


_ENTITYIDENTIFIER = DESCRIPTOR.message_types_by_name['EntityIdentifier']
_DRIVINGDIMENSION = DESCRIPTOR.message_types_by_name['DrivingDimension']
_DESIGN = DESCRIPTOR.message_types_by_name['Design']
EntityIdentifier = _reflection.GeneratedProtocolMessageType('EntityIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _ENTITYIDENTIFIER,
  '__module__' : 'ansys.api.dbu.v0.dbumodels_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.dbu.v0.EntityIdentifier)
  })
_sym_db.RegisterMessage(EntityIdentifier)

DrivingDimension = _reflection.GeneratedProtocolMessageType('DrivingDimension', (_message.Message,), {
  'DESCRIPTOR' : _DRIVINGDIMENSION,
  '__module__' : 'ansys.api.dbu.v0.dbumodels_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.dbu.v0.DrivingDimension)
  })
_sym_db.RegisterMessage(DrivingDimension)

Design = _reflection.GeneratedProtocolMessageType('Design', (_message.Message,), {
  'DESCRIPTOR' : _DESIGN,
  '__module__' : 'ansys.api.dbu.v0.dbumodels_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.dbu.v0.Design)
  })
_sym_db.RegisterMessage(Design)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\020Ansys.Api.Dbu.V0'
  _DIMENSIONTYPE._serialized_start=440
  _DIMENSIONTYPE._serialized_end=740
  _IMAGEFORMAT._serialized_start=742
  _IMAGEFORMAT._serialized_end=798
  _WINDOWVIEW._serialized_start=801
  _WINDOWVIEW._serialized_end=1014
  _ENTITYIDENTIFIER._serialized_start=54
  _ENTITYIDENTIFIER._serialized_end=84
  _DRIVINGDIMENSION._serialized_start=86
  _DRIVINGDIMENSION._serialized_end=212
  _DESIGN._serialized_start=215
  _DESIGN._serialized_end=437
# @@protoc_insertion_point(module_scope)
