# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/dbu/v0/designs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ansys.api.dbu.v0 import dbumodels_pb2 as ansys_dot_api_dot_dbu_dot_v0_dot_dbumodels__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61nsys/api/dbu/v0/designs.proto\x12\x18\x61nsys.api.dbu.v0.designs\x1a ansys/api/dbu/v0/dbumodels.proto\x1a\x1bgoogle/protobuf/empty.proto\";\n\x0eGetAllResponse\x12)\n\x07\x64\x65signs\x18\x01 \x03(\x0b\x32\x18.ansys.api.dbu.v0.Design\"\x1f\n\x0bOpenRequest\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\"\x1a\n\nNewRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\rSaveAsRequest\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\"!\n\rInsertRequest\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\"\x1e\n\x10GetAsJsonRequest\x12\n\n\x02id\x18\x01 \x01(\t\"!\n\x11GetAsJsonResponse\x12\x0c\n\x04json\x18\x01 \x01(\t2\xd9\x06\n\x07\x44\x65signs\x12\x43\n\x03Get\x12\".ansys.api.dbu.v0.EntityIdentifier\x1a\x18.ansys.api.dbu.v0.Design\x12J\n\x06GetAll\x12\x16.google.protobuf.Empty\x1a(.ansys.api.dbu.v0.designs.GetAllResponse\x12=\n\tGetActive\x12\x16.google.protobuf.Empty\x1a\x18.ansys.api.dbu.v0.Design\x12G\n\tPutActive\x12\".ansys.api.dbu.v0.EntityIdentifier\x1a\x16.google.protobuf.Empty\x12Q\n\x04Open\x12%.ansys.api.dbu.v0.designs.OpenRequest\x1a\".ansys.api.dbu.v0.EntityIdentifier\x12\x45\n\x03New\x12$.ansys.api.dbu.v0.designs.NewRequest\x1a\x18.ansys.api.dbu.v0.Design\x12\x43\n\x05\x43lose\x12\".ansys.api.dbu.v0.EntityIdentifier\x1a\x16.google.protobuf.Empty\x12\x42\n\x04Save\x12\".ansys.api.dbu.v0.EntityIdentifier\x1a\x16.google.protobuf.Empty\x12U\n\x06SaveAs\x12\'.ansys.api.dbu.v0.designs.SaveAsRequest\x1a\".ansys.api.dbu.v0.EntityIdentifier\x12U\n\x06Insert\x12\'.ansys.api.dbu.v0.designs.InsertRequest\x1a\".ansys.api.dbu.v0.EntityIdentifier\x12\x64\n\tGetAsJson\x12*.ansys.api.dbu.v0.designs.GetAsJsonRequest\x1a+.ansys.api.dbu.v0.designs.GetAsJsonResponseB\x1b\xaa\x02\x18\x41nsys.Api.Dbu.V0.Designsb\x06proto3')



_GETALLRESPONSE = DESCRIPTOR.message_types_by_name['GetAllResponse']
_OPENREQUEST = DESCRIPTOR.message_types_by_name['OpenRequest']
_NEWREQUEST = DESCRIPTOR.message_types_by_name['NewRequest']
_SAVEASREQUEST = DESCRIPTOR.message_types_by_name['SaveAsRequest']
_INSERTREQUEST = DESCRIPTOR.message_types_by_name['InsertRequest']
_GETASJSONREQUEST = DESCRIPTOR.message_types_by_name['GetAsJsonRequest']
_GETASJSONRESPONSE = DESCRIPTOR.message_types_by_name['GetAsJsonResponse']
GetAllResponse = _reflection.GeneratedProtocolMessageType('GetAllResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETALLRESPONSE,
  '__module__' : 'ansys.api.dbu.v0.designs_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.dbu.v0.designs.GetAllResponse)
  })
_sym_db.RegisterMessage(GetAllResponse)

OpenRequest = _reflection.GeneratedProtocolMessageType('OpenRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPENREQUEST,
  '__module__' : 'ansys.api.dbu.v0.designs_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.dbu.v0.designs.OpenRequest)
  })
_sym_db.RegisterMessage(OpenRequest)

NewRequest = _reflection.GeneratedProtocolMessageType('NewRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEWREQUEST,
  '__module__' : 'ansys.api.dbu.v0.designs_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.dbu.v0.designs.NewRequest)
  })
_sym_db.RegisterMessage(NewRequest)

SaveAsRequest = _reflection.GeneratedProtocolMessageType('SaveAsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAVEASREQUEST,
  '__module__' : 'ansys.api.dbu.v0.designs_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.dbu.v0.designs.SaveAsRequest)
  })
_sym_db.RegisterMessage(SaveAsRequest)

InsertRequest = _reflection.GeneratedProtocolMessageType('InsertRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSERTREQUEST,
  '__module__' : 'ansys.api.dbu.v0.designs_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.dbu.v0.designs.InsertRequest)
  })
_sym_db.RegisterMessage(InsertRequest)

GetAsJsonRequest = _reflection.GeneratedProtocolMessageType('GetAsJsonRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETASJSONREQUEST,
  '__module__' : 'ansys.api.dbu.v0.designs_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.dbu.v0.designs.GetAsJsonRequest)
  })
_sym_db.RegisterMessage(GetAsJsonRequest)

GetAsJsonResponse = _reflection.GeneratedProtocolMessageType('GetAsJsonResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETASJSONRESPONSE,
  '__module__' : 'ansys.api.dbu.v0.designs_pb2'
  # @@protoc_insertion_point(class_scope:ansys.api.dbu.v0.designs.GetAsJsonResponse)
  })
_sym_db.RegisterMessage(GetAsJsonResponse)

_DESIGNS = DESCRIPTOR.services_by_name['Designs']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\030Ansys.Api.Dbu.V0.Designs'
  _GETALLRESPONSE._serialized_start=123
  _GETALLRESPONSE._serialized_end=182
  _OPENREQUEST._serialized_start=184
  _OPENREQUEST._serialized_end=215
  _NEWREQUEST._serialized_start=217
  _NEWREQUEST._serialized_end=243
  _SAVEASREQUEST._serialized_start=245
  _SAVEASREQUEST._serialized_end=278
  _INSERTREQUEST._serialized_start=280
  _INSERTREQUEST._serialized_end=313
  _GETASJSONREQUEST._serialized_start=315
  _GETASJSONREQUEST._serialized_end=345
  _GETASJSONRESPONSE._serialized_start=347
  _GETASJSONRESPONSE._serialized_end=380
  _DESIGNS._serialized_start=383
  _DESIGNS._serialized_end=1240
# @@protoc_insertion_point(module_scope)
