[tool.mypy]
strict = true
files = [
    "src/**/*.py",
    "tests/**/*.py",
]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79

[tool.black]
line-length = 79

[tool.pytest.ini_options]
norecursedirs = "tests/helpers"
pythonpath = [ "src" ]

[tool.poetry]
name = "fladrif"
version = "0.2.0"
description = "Compute a series of operations to transform one tree into another"
authors = ["Sam Wilson <sam@binarycake.ca>"]
license = "GPL-2.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
mypy = "~1.4.1"
isort = "~5.12.0"
black = "~23.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
