
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-14T11:38:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "730c967cfeee6034e0543d428a4d0c09f55e4f00",
 "version": "1.18.4.post0.dev119"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
