
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-11T03:41:08-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd26ddc95491afe940fd0ac1ec32d8dada22a8ac",
 "version": "2.5.53"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
