
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-09T13:04:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2890574f4261bf05568972d12232da08337e15e9",
 "version": "0.4.0.post0.dev119"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
