"""
@author: lijc210@163.com
@file: sort_fields.py
@time: 2019/11/12
@desc: 功能描述。
"""
d = {
    "lock_rule": {
        "describe_api_name": "LeadsObj",
        "is_index": False,
        "is_active": True,
        "create_time": 1561215074760,
        "description": "\u9501\u5b9a\u89c4\u5219",
        "is_unique": False,
        "default_value": "default_lock_rule",
        "rules": [],
        "label": "\u9501\u5b9a\u89c4\u5219",
        "type": "lock_rule",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "lock_rule",
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "index_name": "s_9",
    },
    "leads_pool_id": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750494930,
        "description": "\u7ebf\u7d22\u6c60",
        "is_unique": False,
        "label": "\u7ebf\u7d22\u6c60",
        "type": "select_one",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "leads_pool_id",
        "options": [
            {
                "label": "\u7ef5\u9633\u5e02",
                "value": "042079c08c1d418491f496014b0b9c39",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5357\u660c\u5e02",
                "value": "065c9d2d1220413196d9d2e19be16830",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5f90\u5dde\u5e02",
                "value": "0be64708563d43ba863e47c8b97db126",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6df1\u5733\u5e02",
                "value": "0dd1d24556a0421c86337353930167e5",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6d1b\u9633\u5e02",
                "value": "0f98afa57e1148659074d658b7952c7f",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5b5d\u611f\u5e02",
                "value": "10784e5de9fe460b99ee72210ac68720",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5357\u4eac\u5e02",
                "value": "10d443ea58214f12a7808ef66d253f75",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u957f\u6625\u5e02",
                "value": "12bbd9f9a1244f41a6c065f09c26dd2d",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u961c\u9633\u5e02",
                "value": "16cd9eb66d464514b05d44cd7a5b02d2",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u547c\u548c\u6d69\u7279\u5e02",
                "value": "187cb1853ec549f3beeadb09091df7fe",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6606\u660e\u5e02",
                "value": "1a645ea148564d4b87531ae7a8a85bb2",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5185\u6c5f\u5e02",
                "value": "20183ddbf8ff4c759fbe998dc335c475",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u60e0\u5dde\u5e02",
                "value": "216494f2172544ad92ab8528218d84ba",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u8346\u5dde\u5e02",
                "value": "271e9591c98b463e8d5f12f1a77e93c5",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5609\u5174\u5e02",
                "value": "29b516c3ac90479a9ff9856f2924e68c",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6cc9\u5dde\u5e02",
                "value": "2a094694bad54a83b1bca0f22d1072e5",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5357\u5b81\u5e02",
                "value": "2cd2bfee128a4d658f3048109f8e57c1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u90d1\u5dde\u5e02",
                "value": "2cd52f1b87004704914e0a167e82127a",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6f33\u5dde\u5e02",
                "value": "2d2ee271a62e4b2889510f4d01c073ae",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u9547\u6c5f\u5e02",
                "value": "2d64abb85e964cda9b167a3c9803bb8c",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5eca\u574a\u5e02",
                "value": "2fa0249a5aa243cdb9880b02b2b92c7e",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u82cf\u5dde\u5e02",
                "value": "30628f876dec47dda279bfe0ba9fa66a",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u91cd\u5e86\u5e02",
                "value": "33f1b02dabbc4db3ba895df1c087bc08",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u8944\u9633\u5e02",
                "value": "3dc4ce0764e449df8f65845564183fbf",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6dee\u5b89\u5e02",
                "value": "3e4ad4a8cab64f7bb211accdf2fcc216",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6e56\u5dde\u5e02",
                "value": "3e9c1d035180489eaf1304dcc8798140",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u676d\u5dde\u5e02",
                "value": "3f1418e9303d44f286d9a3406ec4d395",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u9075\u4e49\u5e02",
                "value": "4a31cca0c32240d79cc6360eaea56305",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5408\u80a5\u5e02",
                "value": "4cbab5924222423b9959899cf00bd66a",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5170\u5dde\u5e02",
                "value": "52ed71cd3e244969861cfc1c1b0b971b",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u978d\u5c71\u5e02",
                "value": "573732597b0e448595900e9a131d6ea1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6210\u90fd\u5e02",
                "value": "5fbe65a102384a1fa224e18fb3aeb886",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6e29\u5dde\u5e02",
                "value": "62744b2b5f48405f8cd5ed0e9bdd7593",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u4e2d\u5c71\u5e02",
                "value": "63a4a4aef7304b98aef6c6cf0ea11eb9",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5e38\u5dde\u5e02",
                "value": "6415030993844dc2a9ce5869cb1f4ecf",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5e9f\u5f03\u7ebf\u7d22\u6c60-\u9648\u53cb\u4e49",
                "value": "67ce9d1a091e496f8090cffcd5d9283c",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u957f\u6c99\u5e02",
                "value": "6a77315b0d0945fc9c4f37587ee9ff69",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6b66\u6c49\u5e02",
                "value": "705271acf99d4b818a4e81c98ce4d86b",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u4fdd\u5b9a\u5e02",
                "value": "70b714b484294c3fa80e484795209bd8",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u592a\u539f\u5e02",
                "value": "80e8993a2d444f618854c69ed83de81b",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5f31\u5316\u7ebf\u7d22\u6c60",
                "value": "82539a763a3342859e4ecdabd521b727",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u8d35\u9633\u5e02",
                "value": "8296328e15a6474eb652808f730b5c24",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5b81\u6ce2\u5e02",
                "value": "85fe91bba0924808ba97b88541fdad5d",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5357\u901a\u5e02",
                "value": "8921d64d87d9438b9555e9714f63c776",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u682a\u6d32\u5e02",
                "value": "8f7c6c76239c45128ece6a7ff3f52c20",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6f4d\u574a\u5e02",
                "value": "90f02f70eea84a9daf1d36c4bb6b2f1b",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5317\u4eac\u5e02",
                "value": "9c1db9bb74fa4f9c9d5a6cd5d3bf783a",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6d4e\u5357\u5e02",
                "value": "a13bbd5c53874c0baad2eeeb9a9e0d17",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u65e0\u9521\u5e02",
                "value": "aa715c8bbe854ddfa7a38e4413921297",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u94f6\u5ddd\u5e02",
                "value": "ad740c82706d4f3b894c1bdffe9d5d1d",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u9ec4\u77f3\u5e02",
                "value": "ae6e546ada7b40e2bbc56f8fda6d849e",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u7535\u9500\u7ebf\u7d22\u6c60",
                "value": "b5b9cf4ee8874a05b689b485177b25c9",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5929\u6d25\u5e02",
                "value": "b7394807ee0542fbb349155f27483120",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u4f5b\u5c71\u5e02",
                "value": "bc5da580532949b9b4519c1fcfa9504c",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u4e5d\u6c5f\u5e02",
                "value": "bcb50cc8bf404680bf3f8754650b441f",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u70df\u53f0\u5e02",
                "value": "bd856e50391c4e388337ce6cda508bed",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5357\u5145\u5e02",
                "value": "c784465542fe489e8645092fcea46711",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u54c8\u5c14\u6ee8\u5e02",
                "value": "cd71885527fd438385b71c0cff7e6ca6",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u9752\u5c9b\u5e02",
                "value": "d1c4084ae31a49d79328e8f461a515da",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u4e1c\u839e\u5e02",
                "value": "d4359bdfcc8f405299052c65f0c2173f",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u53f0\u5dde\u5e02",
                "value": "d5681d147c764d5d802c32b5857c2507",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u798f\u5dde\u5e02",
                "value": "ddad23a3dd6444e88acfbad37712409d",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u53a6\u95e8\u5e02",
                "value": "e202335802734149845eccaf7846ee0e",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5927\u8fde\u5e02",
                "value": "e21ca421c3574a70948c222e1f94e900",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u65e0\u6548\u7ebf\u7d22\u6c60",
                "value": "e53b1b98d5534ac4b0e43763ba3185ae",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6c88\u9633\u5e02",
                "value": "ea05e0b1c429470f91cae15b58cd6a62",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u77f3\u5bb6\u5e84\u5e02",
                "value": "efe03e7bb0c44a4bb9e98d0deda85502",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5b9d\u9e21\u5e02",
                "value": "f1e32c9805e34680b956fef2479573e7",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u4e0a\u6d77\u5e02",
                "value": "f333fc0b0fbf40858fad9a0b78c3cfe8",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u7ecd\u5174\u5e02",
                "value": "f3d8cc46c171408691061e1644e9d193",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u76d0\u57ce\u5e02",
                "value": "fb29d153bc494d7bbd1582795e9311ad",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u897f\u5b89\u5e02",
                "value": "fba12a80435646d99746ed924ef48abb",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u626c\u5dde\u5e02",
                "value": "fbe471c990e34ef2b33f315b1d8c7ed1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5e7f\u5dde\u5e02",
                "value": "ff5fe2b68dc64802b68d8851df13a5ca",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 1,
            "attrs": {"wheres": 1, "is_required": True, "label": 1, "help_text": 1},
        },
        "index_name": "s_6",
    },
    "assigner_id": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750494930,
        "length": 18,
        "description": "\u5206\u914d\u7ba1\u7406\u5458",
        "is_unique": False,
        "label": "\u5206\u914d\u7ba1\u7406\u5458",
        "type": "employee",
        "decimal_places": 0,
        "is_need_convert": True,
        "is_required": False,
        "api_name": "assigner_id",
        "define_type": "system",
        "is_index_field": False,
        "is_single": True,
        "config": {
            "edit": 0,
            "enable": 0,
            "display": 1,
            "attrs": {"wheres": 1, "is_required": True, "label": 1, "help_text": 1},
        },
        "index_name": "a_1",
        "round_mode": 4,
    },
    "UDSText5__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750494930,
        "pattern": "",
        "description": "\u516c\u53f8\u8d44\u8d28",
        "is_unique": False,
        "label": "\u516c\u53f8\u8d44\u8d28",
        "type": "text",
        "field_num": 5,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDSText5__c",
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "t_13",
        "max_length": 100,
    },
    "UDSText9__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750494930,
        "pattern": "",
        "description": "\u516c\u53f8\u5730\u5740",
        "is_unique": False,
        "label": "\u516c\u53f8\u5730\u5740",
        "type": "text",
        "field_num": 9,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDSText9__c",
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "t_15",
        "max_length": 100,
    },
    "transform_time": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750494930,
        "description": "\u8f6c\u6362\u65f6\u95f4",
        "is_unique": False,
        "label": "\u8f6c\u6362\u65f6\u95f4",
        "time_zone": "GMT+8",
        "type": "date_time",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "transform_time",
        "define_type": "system",
        "date_format": "yyyy-MM-dd HH:mm:ss",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 0,
            "display": 1,
            "attrs": {
                "wheres": 1,
                "is_required": True,
                "default_value": 1,
                "label": 1,
                "help_text": 1,
            },
        },
        "index_name": "l_5",
    },
    "source": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750494943,
        "description": "\u6765\u6e90",
        "is_unique": False,
        "default_value": "",
        "label": "\u6765\u6e90",
        "type": "select_one",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "source",
        "options": [
            {
                "label": "400",
                "value": "4",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u7ebf\u4e0a",
                "value": "5",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u81ea\u5f00\u62d3",
                "value": "8",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5916\u90e8",
                "value": "9",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "not_usable": False,
                "label": "\u673a\u5668",
                "value": "tk08702Z1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "not_usable": False,
                "label": "\u5c0f\u7a0b\u5e8f",
                "value": "WA03M1qle",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "add": 1,
            "edit": 1,
            "enable": 0,
            "display": 1,
            "remove": 0,
            "attrs": {
                "wheres": 1,
                "is_required": True,
                "api_name": 0,
                "options": 1,
                "is_unique": 0,
                "default_value": 0,
                "label": 1,
                "help_text": 1,
            },
        },
        "index_name": "s_17",
        "help_text": "",
    },
    "extend_obj_data_id": {
        "describe_api_name": "LeadsObj",
        "default_is_expression": False,
        "is_index": False,
        "is_active": True,
        "create_time": 1530510400372,
        "pattern": "",
        "description": "extend_obj_data_id",
        "is_unique": False,
        "default_value": "",
        "label": "extend_obj_data_id",
        "type": "text",
        "default_to_zero": False,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "extend_obj_data_id",
        "define_type": "system",
        "is_extend": False,
        "is_single": False,
        "is_index_field": False,
        "index_name": "t_5",
        "max_length": 200,
        "help_text": "",
    },
    "owner_change_time": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750494943,
        "description": "\u8d1f\u8d23\u4eba\u53d8\u66f4\u65f6\u95f4",
        "is_unique": False,
        "label": "\u8d1f\u8d23\u4eba\u53d8\u66f4\u65f6\u95f4",
        "time_zone": "GMT+8",
        "type": "date_time",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "owner_change_time",
        "define_type": "system",
        "date_format": "yyyy-MM-dd HH:mm:ss",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 0,
            "display": 1,
            "default_value": 1,
            "attrs": {"wheres": 1, "is_required": False, "label": 1, "help_text": 1},
        },
        "index_name": "l_4",
    },
    "life_status_before_invalid": {
        "describe_api_name": "LeadsObj",
        "is_index": False,
        "is_active": True,
        "create_time": 1561215074792,
        "pattern": "",
        "description": "\u4f5c\u5e9f\u524d\u751f\u547d\u72b6\u6001",
        "is_unique": False,
        "label": "\u4f5c\u5e9f\u524d\u751f\u547d\u72b6\u6001",
        "type": "text",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "life_status_before_invalid",
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "index_name": "t_7",
        "max_length": 256,
    },
    "owner_department": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750494943,
        "pattern": "",
        "description": "\u8d1f\u8d23\u4eba\u4e3b\u5c5e\u90e8\u95e8",
        "is_unique": False,
        "label": "\u8d1f\u8d23\u4eba\u4e3b\u5c5e\u90e8\u95e8",
        "type": "text",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "owner_department",
        "define_type": "system",
        "is_index_field": False,
        "is_single": False,
        "config": {"edit": 0, "display": 1, "attrs": {"wheres": 1, "help_text": 1}},
        "index_name": "owner_dept",
        "max_length": 100,
    },
    "remind_days": {
        "describe_api_name": "LeadsObj",
        "is_index": False,
        "is_active": True,
        "create_time": 1566478252650,
        "length": 8,
        "description": "\u56de\u6536\u63d0\u524d\u63d0\u9192\u5929\u6570",
        "is_unique": False,
        "label": "\u56de\u6536\u63d0\u524d\u63d0\u9192\u5929\u6570",
        "type": "number",
        "decimal_places": 0,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "remind_days",
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 0,
            "enable": 0,
            "display": 0,
            "remove": 0,
            "attrs": {
                "wheres": 0,
                "is_required": 0,
                "default_value": 0,
                "help_text": 0,
            },
        },
        "round_mode": 4,
    },
    "tel": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750494943,
        "pattern": "^[0-9+\\-;,]{0,100}$",
        "description": "\u7535\u8bdd",
        "is_unique": False,
        "label": "\u7535\u8bdd",
        "type": "phone_number",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "tel",
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 1,
            "attrs": {"wheres": 1, "is_required": True, "label": 1, "help_text": 1},
        },
        "index_name": "p_2",
    },
    "UDSSel3__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750494954,
        "description": "\u65e0\u6548\u8ddf\u8fdb\u7ed3\u679c",
        "is_unique": False,
        "label": "\u65e0\u6548\u8ddf\u8fdb\u7ed3\u679c",
        "type": "select_one",
        "field_num": 183,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDSSel3__c",
        "options": [
            {
                "label": "\u7a7a\u53f7\u9519\u53f7",
                "value": "1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u65e0\u4eba\u63a5\u542c",
                "value": "2",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u62d2\u8bbf",
                "value": "4",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u91cd\u590d\u4fe1\u606f",
                "value": "5",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u65e0\u9700\u6c42",
                "value": "9",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u65bd\u5de5\u961f",
                "value": "11",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u4e1a\u4e3b\u88c5\u4fee",
                "value": "12",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6750\u6599\u5546\u60f3\u5408\u4f5c",
                "value": "13",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5546\u5bb6\u62d2\u7edd\u5408\u4f5c",
                "value": "14",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "s_21",
        "config": {},
    },
    "assigned_time": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750494955,
        "description": "\u9886\u53d6/\u5206\u914d\u65f6\u95f4",
        "is_unique": False,
        "label": "\u9886\u53d6/\u5206\u914d\u65f6\u95f4",
        "time_zone": "GMT+8",
        "type": "date_time",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "assigned_time",
        "define_type": "package",
        "date_format": "yyyy-MM-dd HH:mm:ss",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 0,
            "display": 1,
            "default_value": 1,
            "attrs": {"wheres": 1, "is_required": True, "help_text": 1},
        },
        "index_name": "l_1",
    },
    "job_title": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": False,
        "create_time": 1560750494955,
        "pattern": "",
        "description": "\u804c\u52a1",
        "is_unique": False,
        "label": "\u804c\u52a1",
        "type": "text",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "job_title",
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 1,
            "enable": 1,
            "attrs": {"wheres": 1, "is_required": True, "label": 1, "help_text": 1},
        },
        "index_name": "t_6",
        "max_length": 100,
    },
    "UDSSel7__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": False,
        "create_time": 1560750494962,
        "description": "\u662f\u5426\u5e74\u540e\u8054\u7cfb",
        "is_unique": False,
        "label": "\u662f\u5426\u5e74\u540e\u8054\u7cfb",
        "type": "select_one",
        "field_num": 187,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDSSel7__c",
        "options": [
            {
                "label": "\u662f",
                "value": "1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5426",
                "value": "2",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "s_25",
        "config": {},
    },
    "UDMSel3__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750494979,
        "description": "\u63a5\u5355\u533a\u57df",
        "is_unique": False,
        "label": "\u63a5\u5355\u533a\u57df",
        "type": "select_many",
        "field_num": 233,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDMSel3__c",
        "options": [
            {
                "label": "\u5e02\u533a",
                "value": "1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u8fd1\u90ca",
                "value": "2",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u8fdc\u90ca",
                "value": "3",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "a_7",
        "config": {},
    },
    "biz_status": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1561215074815,
        "description": "\u72b6\u6001",
        "is_unique": False,
        "default_value": "un_assigned",
        "label": "\u72b6\u6001",
        "type": "select_one",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "biz_status",
        "options": [
            {
                "label": "\u672a\u5206\u914d",
                "value": "un_assigned",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5f85\u5904\u7406",
                "value": "un_processed",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5df2\u8f6c\u6362",
                "value": "transformed",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u8ddf\u8fdb\u4e2d",
                "value": "processed",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u65e0\u6548",
                "value": "closed",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 0,
            "display": 1,
            "attrs": {"wheres": 1, "is_required": True, "help_text": 1},
        },
        "index_name": "s_3",
    },
    "lock_status": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750494989,
        "description": "\u9501\u5b9a\u72b6\u6001",
        "is_unique": False,
        "default_value": "0",
        "label": "\u9501\u5b9a\u72b6\u6001",
        "type": "select_one",
        "is_required": False,
        "api_name": "lock_status",
        "options": [
            {
                "label": "\u672a\u9501\u5b9a",
                "value": "0",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u9501\u5b9a",
                "value": "1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "system",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 0,
            "display": 1,
            "attrs": {"wheres": 1, "is_required": False, "help_text": 1},
        },
        "index_name": "s_10",
    },
    "create_time": {
        "is_index": True,
        "create_time": 1530510400372,
        "is_unique": False,
        "description": "create_time",
        "label": "\u521b\u5efa\u65f6\u95f4",
        "type": "date_time",
        "time_zone": "",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "create_time",
        "define_type": "system",
        "date_format": "yyyy-MM-dd HH:mm:ss",
        "index_name": "crt_time",
    },
    "new_opportunity_id": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": False,
        "create_time": 1560750494989,
        "description": "\u5546\u673a2.0",
        "is_unique": False,
        "label": "\u5546\u673a2.0",
        "target_api_name": "NewOpportunityObj",
        "type": "object_reference",
        "target_related_list_name": "new_opportunity_leads_list",
        "target_related_list_label": "\u9500\u552e\u7ebf\u7d22",
        "action_on_target_delete": "cascade_delete",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "new_opportunity_id",
        "define_type": "system",
        "is_index_field": False,
        "is_single": False,
        "config": {"display": 0},
        "index_name": "s_12",
    },
    "expire_time": {
        "describe_api_name": "LeadsObj",
        "is_index": False,
        "is_active": True,
        "create_time": 1561215074819,
        "description": "expire_time",
        "is_unique": False,
        "label": "\u9884\u8ba1\u6536\u56de\u65f6\u95f4",
        "time_zone": "",
        "type": "date_time",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "expire_time",
        "define_type": "package",
        "date_format": "yyyy-MM-dd HH:mm:ss",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 0,
            "enable": 0,
            "display": 1,
            "remove": 0,
            "attrs": {
                "wheres": 1,
                "is_required": 0,
                "default_value": 1,
                "help_text": 1,
            },
        },
        "index_name": "l_2",
    },
    "created_by": {
        "is_index": True,
        "is_active": True,
        "create_time": 1530510400372,
        "is_unique": False,
        "label": "\u521b\u5efa\u4eba",
        "type": "employee",
        "is_need_convert": True,
        "is_required": False,
        "api_name": "created_by",
        "define_type": "system",
        "is_single": True,
        "index_name": "crt_by",
    },
    "relevant_team": {
        "describe_api_name": "LeadsObj",
        "embedded_fields": {
            "teamMemberEmployee": {
                "is_index": True,
                "is_need_convert": True,
                "is_required": False,
                "api_name": "teamMemberEmployee",
                "is_unique": False,
                "define_type": "package",
                "description": "\u6210\u5458\u5458\u5de5",
                "label": "\u6210\u5458\u5458\u5de5",
                "type": "employee",
                "is_single": False,
                "index_name": "stringList_2",
                "help_text": "\u6210\u5458\u5458\u5de5",
            },
            "teamMemberRole": {
                "is_index": True,
                "is_need_convert": False,
                "is_required": False,
                "api_name": "teamMemberRole",
                "options": [
                    {"label": "\u8d1f\u8d23\u4eba", "value": "1"},
                    {"label": "\u666e\u901a\u6210\u5458", "value": "4"},
                ],
                "is_unique": False,
                "define_type": "package",
                "description": "\u6210\u5458\u89d2\u8272",
                "label": "\u6210\u5458\u89d2\u8272",
                "type": "select_one",
                "index_name": "string_4",
                "help_text": "\u6210\u5458\u89d2\u8272",
            },
            "teamMemberPermissionType": {
                "is_index": True,
                "is_need_convert": False,
                "is_required": False,
                "api_name": "teamMemberPermissionType",
                "options": [
                    {"label": "\u53ea\u8bfb", "value": "1"},
                    {"label": "\u8bfb\u5199", "value": "2"},
                ],
                "is_unique": False,
                "define_type": "package",
                "description": "\u6210\u5458\u6743\u9650\u7c7b\u578b",
                "label": "\u6210\u5458\u6743\u9650\u7c7b\u578b",
                "type": "select_one",
                "index_name": "string_5",
                "help_text": "\u6210\u5458\u6743\u9650\u7c7b\u578b",
            },
        },
        "is_index": True,
        "is_active": True,
        "create_time": 1560750494989,
        "is_unique": False,
        "label": "\u76f8\u5173\u56e2\u961f",
        "type": "embedded_object_list",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "relevant_team",
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "index_name": "a_team",
        "help_text": "\u76f8\u5173\u56e2\u961f",
    },
    "remaining_time": {
        "describe_api_name": "LeadsObj",
        "pattern": "",
        "description": "\u5269\u4f59\u4fdd\u6709\u65f6\u95f4\uff08\u5c0f\u65f6\uff09",
        "is_unique": False,
        "type": "number",
        "decimal_places": 0,
        "default_to_zero": True,
        "is_required": False,
        "define_type": "package",
        "is_single": False,
        "index_name": "d_1",
        "max_length": 14,
        "is_index": True,
        "expression": "date_part('hour',to_timestamp(LeadsObj.expire_time/1000) - now() :: TIMESTAMP)",
        "is_active": True,
        "create_time": 1561215074819,
        "length": 14,
        "label": "\u5269\u4f59\u4fdd\u6709\u65f6\u95f4\uff08\u5c0f\u65f6\uff09",
        "is_abstract": True,
        "is_need_convert": False,
        "api_name": "remaining_time",
        "is_index_field": False,
        "config": {
            "edit": 0,
            "enable": 0,
            "display": 1,
            "remove": 0,
            "attrs": {
                "wheres": 1,
                "is_required": 0,
                "default_value": 1,
                "help_text": 1,
            },
        },
        "round_mode": 4,
    },
    "opportunity_id": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750494989,
        "description": "\u5546\u673a\u540d\u79f0",
        "is_unique": False,
        "label": "\u5546\u673a\u540d\u79f0",
        "target_api_name": "OpportunityObj",
        "type": "object_reference",
        "target_related_list_name": "opportunity_leads_list",
        "target_related_list_label": "\u9500\u552e\u7ebf\u7d22",
        "action_on_target_delete": "cascade_delete",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "opportunity_id",
        "define_type": "system",
        "is_index_field": False,
        "is_single": False,
        "config": {"display": 0},
        "index_name": "s_13",
    },
    "data_own_department": {
        "is_index": True,
        "is_active": True,
        "create_time": 1530510400372,
        "is_unique": False,
        "label": "\u5f52\u5c5e\u90e8\u95e8",
        "type": "department",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "data_own_department",
        "define_type": "package",
        "is_single": True,
        "index_name": "data_owner_dept_id",
    },
    "back_reason": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": False,
        "create_time": 1560750494996,
        "description": "\u9500\u552e\u4eba\u5458\u9000\u56de\u539f\u56e0",
        "is_unique": False,
        "label": "\u9500\u552e\u4eba\u5458\u9000\u56de\u539f\u56e0",
        "type": "select_one",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "back_reason",
        "options": [
            {
                "label": "\u8054\u7cfb\u4e0d\u4e0a\u5ba2\u6237",
                "value": "0",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5ba2\u6237\u6682\u65e0\u9700\u6c42",
                "value": "1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u672a\u6ee1\u8db3\u5ba2\u6237\u9700\u6c42",
                "value": "2",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5176\u5b83",
                "value": "3",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "add": 1,
            "edit": 1,
            "enable": 1,
            "attrs": {
                "wheres": 1,
                "is_required": False,
                "options": 1,
                "label": 1,
                "help_text": 1,
            },
        },
        "index_name": "s_2",
    },
    "last_follow_time": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750494996,
        "description": "\u6700\u540e\u8ddf\u8fdb\u65f6\u95f4",
        "is_unique": False,
        "label": "\u6700\u540e\u8ddf\u8fdb\u65f6\u95f4",
        "time_zone": "GMT+8",
        "type": "date_time",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "last_follow_time",
        "define_type": "system",
        "date_format": "yyyy-MM-dd HH:mm:ss",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 0,
            "display": 1,
            "attrs": {"wheres": 1, "is_required": True, "label": 1, "help_text": 1},
        },
        "index_name": "l_3",
    },
    "name": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750494996,
        "pattern": "",
        "description": "\u59d3\u540d",
        "is_unique": False,
        "label": "\u59d3\u540d",
        "type": "text",
        "is_need_convert": False,
        "is_required": True,
        "api_name": "name",
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 1,
            "attrs": {"wheres": 1, "is_required": False, "label": 1, "help_text": 1},
        },
        "index_name": "name",
        "max_length": 100,
    },
    "leads_status": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_use_value": True,
        "expression": "CASE($life_status$, 'ineffective','6', 'under_review','7','in_change','8', 'invalid','99','normal',CASE($biz_status$,'un_assigned','1','un_processed','2','transformed','3','processed','4','closed','5','1'),'1' )",
        "is_active": True,
        "create_time": 1560750495007,
        "description": "\u72b6\u6001\uff08\u539f\uff09",
        "is_unique": False,
        "label": "\u72b6\u6001\uff08\u539f\uff09",
        "type": "select_one",
        "is_need_convert": False,
        "is_need_calculate": True,
        "is_required": False,
        "api_name": "leads_status",
        "options": [
            {
                "label": "\u672a\u5206\u914d",
                "value": "1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5f85\u5904\u7406",
                "value": "2",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5df2\u8f6c\u6362",
                "value": "3",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u8ddf\u8fdb\u4e2d",
                "value": "4",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u65e0\u6548",
                "value": "5",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5df2\u4f5c\u5e9f",
                "value": "99",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u672a\u751f\u6548",
                "value": "6",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5ba1\u6838\u4e2d",
                "value": "7",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u53d8\u66f4\u4e2d",
                "value": "8",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "system",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 0,
            "display": 1,
            "attrs": {"wheres": 1, "is_required": True, "help_text": 1},
        },
        "index_name": "s_7",
    },
    "UDDate1__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495007,
        "description": "\u62a5\u540d\u65e5\u671f",
        "is_unique": False,
        "label": "\u62a5\u540d\u65e5\u671f",
        "time_zone": "GMT+8",
        "type": "date",
        "field_num": 161,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDDate1__c",
        "define_type": "custom",
        "date_format": "yyyy-MM-dd",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "l_6",
    },
    "UDSText1__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495007,
        "pattern": "",
        "description": "\u5ba2\u670d\u4eba\u5458",
        "is_unique": False,
        "label": "\u5ba2\u670d\u4eba\u5458",
        "type": "text",
        "field_num": 1,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDSText1__c",
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "t_10",
        "max_length": 100,
    },
    "close_reason": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495015,
        "description": "\u7ebf\u7d22\u65e0\u6548\u539f\u56e0",
        "is_unique": False,
        "label": "\u7ebf\u7d22\u65e0\u6548\u539f\u56e0",
        "type": "select_one",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "close_reason",
        "options": [
            {
                "label": "\u7a7a\u53f7\u9519\u53f7",
                "value": "0",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u65e0\u4eba\u63a5\u542c",
                "value": "1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u62d2\u8bbf",
                "value": "2",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u91cd\u590d\u4fe1\u606f",
                "value": "3",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u65e0\u9700\u6c42",
                "value": "4",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u65bd\u5de5\u961f",
                "value": "5",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u4e1a\u4e3b\u88c5\u4fee",
                "value": "6",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6750\u6599\u5546\u60f3\u5408\u4f5c",
                "value": "7",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5546\u5bb6\u62d2\u7edd\u5408\u4f5c",
                "value": "8",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "add": 1,
            "edit": 1,
            "enable": 1,
            "attrs": {
                "wheres": 1,
                "is_required": False,
                "options": 1,
                "label": 1,
                "help_text": 1,
            },
        },
        "index_name": "s_4",
    },
    "_id": {
        "is_index": False,
        "create_time": 1530510400372,
        "pattern": "",
        "is_unique": False,
        "description": "_id",
        "label": "_id",
        "type": "text",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "_id",
        "define_type": "system",
        "index_name": "_id",
        "max_length": 200,
    },
    "UDSSel2__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495025,
        "description": "\u7ebf\u4e0b\u6700\u8fd1\u8ddf\u8fdb\u7ed3\u679c",
        "is_unique": False,
        "label": "\u7ebf\u4e0b\u6700\u8fd1\u8ddf\u8fdb\u7ed3\u679c",
        "type": "select_one",
        "field_num": 182,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDSSel2__c",
        "options": [
            {
                "label": "\u6709\u610f\u5411\u6301\u7eed\u8ddf\u8fdb",
                "value": "1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5546\u5bb6\u62d2\u7edd\u5408\u4f5c",
                "value": "2",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6750\u6599\u5546",
                "value": "3",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u65bd\u5de5\u961f",
                "value": "4",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u91cd\u590d\u4fe1\u606f",
                "value": "5",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u7a7a\u53f7\u9519\u53f7",
                "value": "6",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u65e0\u4eba\u63a5\u542c",
                "value": "7",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "s_20",
        "config": {},
    },
    "UDMSel2__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495035,
        "description": "\u63a5\u5355\u623f\u578b",
        "is_unique": False,
        "label": "\u63a5\u5355\u623f\u578b",
        "type": "select_many",
        "field_num": 232,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDMSel2__c",
        "options": [
            {
                "label": "\u4e00\u623f",
                "value": "1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u4e8c\u623f",
                "value": "2",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u4e09\u623f",
                "value": "3",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u56db\u623f",
                "value": "4",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5c0f\u590d\u5f0f",
                "value": "5",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u4e2d\u590d\u5f0f",
                "value": "6",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5927\u590d\u5f0f",
                "value": "7",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "a_6",
        "config": {},
    },
    "UDSSel6__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": False,
        "create_time": 1560750495069,
        "description": "\u5e97\u94fa\u5165\u9a7b\u610f\u5411",
        "is_unique": False,
        "label": "\u5e97\u94fa\u5165\u9a7b\u610f\u5411",
        "type": "select_one",
        "field_num": 186,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDSSel6__c",
        "options": [
            {
                "label": "\u666e\u901a\u5e97",
                "value": "1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u65d7\u8230\u5e97",
                "value": "2",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "s_24",
        "config": {},
    },
    "is_remind_recycling": {
        "describe_api_name": "LeadsObj",
        "is_index": False,
        "is_active": True,
        "create_time": 1561215074877,
        "pattern": "",
        "description": "\u662f\u5426\u5f85\u56de\u6536\u63d0\u9192",
        "is_unique": False,
        "default_value": False,
        "label": "\u662f\u5426\u5f85\u56de\u6536\u63d0\u9192",
        "type": "True_or_False",
        "is_abstract": True,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "is_remind_recycling",
        "options": [
            {"label": "\u5426", "value": False},
            {"label": "\u662f", "value": True},
        ],
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 0,
            "enable": 0,
            "display": 0,
            "remove": 0,
            "attrs": {
                "wheres": 1,
                "is_required": 0,
                "default_value": 1,
                "help_text": 1,
            },
        },
        "index_name": "b_2",
    },
    "remark": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495069,
        "pattern": "",
        "description": "\u9500\u552e\u7ebf\u7d22\u8be6\u60c5",
        "is_unique": False,
        "label": "\u9500\u552e\u7ebf\u7d22\u8be6\u60c5",
        "type": "long_text",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "remark",
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 1,
            "attrs": {"wheres": 1, "is_required": True, "label": 1, "help_text": 1},
        },
        "index_name": "t_8",
        "max_length": 2000,
    },
    "contact_id": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495069,
        "description": "\u8054\u7cfb\u4eba",
        "is_unique": False,
        "label": "\u8054\u7cfb\u4eba",
        "target_api_name": "ContactObj",
        "type": "object_reference",
        "target_related_list_name": "contact_leads_list",
        "target_related_list_label": "\u9500\u552e\u7ebf\u7d22",
        "action_on_target_delete": "cascade_delete",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "contact_id",
        "define_type": "system",
        "is_index_field": False,
        "is_single": False,
        "config": {"display": 0},
        "index_name": "s_5",
    },
    "lock_user": {
        "describe_api_name": "LeadsObj",
        "is_index": False,
        "is_active": True,
        "create_time": 1561215074877,
        "description": "\u52a0\u9501\u4eba",
        "is_unique": False,
        "label": "\u52a0\u9501\u4eba",
        "type": "employee",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "lock_user",
        "define_type": "package",
        "is_index_field": False,
        "is_single": True,
        "index_name": "a_3",
    },
    "resale_count": {
        "describe_api_name": "LeadsObj",
        "is_index": False,
        "is_active": True,
        "create_time": 1561215074877,
        "length": 18,
        "description": "\u7ebf\u7d22\u6570\u91cf",
        "is_unique": False,
        "label": "\u7ebf\u7d22\u6570\u91cf",
        "type": "number",
        "decimal_places": 0,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "resale_count",
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {"display": 0},
        "index_name": "d_2",
        "round_mode": 4,
    },
    "UDSSel1__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495082,
        "description": "\u7ebf\u4e0a\u6700\u8fd1\u56de\u8bbf\u7ed3\u679c",
        "is_unique": False,
        "label": "\u7ebf\u4e0a\u6700\u8fd1\u56de\u8bbf\u7ed3\u679c",
        "type": "select_one",
        "field_num": 181,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDSSel1__c",
        "options": [
            {
                "label": "\u65e0\u4eba\u63a5\u542c",
                "value": "1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u7a7a\u53f7\u9519\u53f7",
                "value": "2",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u4e1a\u4e3b\u88c5\u4fee",
                "value": "3",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6750\u6599\u5546\u60f3\u5408\u4f5c",
                "value": "4",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u88c5\u4fee\u516c\u53f8\u60f3\u5408\u4f5c",
                "value": "5",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u62d2\u8bbf",
                "value": "6",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u65e0\u9700\u6c42",
                "value": "7",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u9080\u7ea6\u6210\u529f",
                "value": "8",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u518d\u8054\u7cfb",
                "value": "9",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "s_19",
        "config": {},
    },
    "partner_id": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": False,
        "create_time": 1560750495082,
        "description": "\u5408\u4f5c\u4f19\u4f34",
        "is_unique": False,
        "label": "\u5408\u4f5c\u4f19\u4f34",
        "target_api_name": "PartnerObj",
        "type": "object_reference",
        "target_related_list_name": "partner_leads_list",
        "target_related_list_label": "\u7ebf\u7d22",
        "action_on_target_delete": "cascade_delete",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "partner_id",
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 1,
            "enable": 0,
            "display": 0,
            "default_value": 1,
            "attrs": {"wheres": 1, "is_required": True, "label": 1, "help_text": 1},
        },
        "index_name": "s_15",
    },
    "is_deleted": {
        "is_index": False,
        "create_time": 1530510400372,
        "is_unique": False,
        "description": "is_deleted",
        "default_value": False,
        "label": "is_deleted",
        "type": "True_or_False",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "is_deleted",
        "define_type": "system",
        "index_name": "is_del",
    },
    "UDDate2__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495082,
        "description": "\u56de\u8bbf\u65f6\u95f4",
        "is_unique": False,
        "label": "\u56de\u8bbf\u65f6\u95f4",
        "time_zone": "GMT+8",
        "type": "date",
        "field_num": 162,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDDate2__c",
        "define_type": "custom",
        "date_format": "yyyy-MM-dd",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "l_7",
    },
    "company": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495082,
        "pattern": "",
        "description": "\u516c\u53f8",
        "is_unique": False,
        "label": "\u516c\u53f8",
        "type": "text",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "company",
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 1,
            "attrs": {"wheres": 1, "is_required": True, "label": 1, "help_text": 1},
        },
        "index_name": "t_2",
        "max_length": 100,
    },
    "UDSText4__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495082,
        "pattern": "",
        "description": "\u60f3\u8981\u5165\u4f4f\u57ce\u5e02",
        "is_unique": False,
        "label": "\u60f3\u8981\u5165\u4f4f\u57ce\u5e02",
        "type": "text",
        "field_num": 4,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDSText4__c",
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "t_12",
        "max_length": 100,
    },
    "out_owner": {
        "is_index": False,
        "create_time": 1530510400372,
        "is_unique": False,
        "label": "\u5916\u90e8\u8d1f\u8d23\u4eba",
        "type": "employee",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "out_owner",
        "define_type": "system",
        "is_single": True,
        "index_name": "o_owner",
        "config": {"display": 1},
    },
    "last_follower": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495082,
        "length": 18,
        "description": "\u6700\u540e\u8ddf\u8fdb\u4eba",
        "is_unique": False,
        "label": "\u6700\u540e\u8ddf\u8fdb\u4eba",
        "type": "employee",
        "decimal_places": 0,
        "is_need_convert": True,
        "is_required": False,
        "api_name": "last_follower",
        "define_type": "system",
        "is_index_field": False,
        "is_single": True,
        "config": {
            "edit": 0,
            "display": 1,
            "attrs": {"wheres": 1, "is_required": True, "label": 1, "help_text": 1},
        },
        "index_name": "a_2",
        "round_mode": 4,
    },
    "out_resources": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": False,
        "create_time": 1560750495089,
        "description": "\u5916\u90e8\u6765\u6e90",
        "is_unique": False,
        "label": "\u5916\u90e8\u6765\u6e90",
        "type": "select_one",
        "is_required": False,
        "api_name": "out_resources",
        "options": [
            {"not_usable": False, "label": "PRM", "value": "partner", "config": {}}
        ],
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 0,
            "enable": 0,
            "display": 0,
            "attrs": {"wheres": 1, "is_required": True, "label": 1, "help_text": 1},
        },
        "index_name": "s_14",
    },
    "UDLookUp1__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495089,
        "description": "\u6700\u8fd1\u56de\u8bbf\u4eba",
        "is_unique": False,
        "label": "\u6700\u8fd1\u56de\u8bbf\u4eba",
        "target_api_name": "PersonnelObj",
        "type": "object_reference",
        "target_related_list_name": "target_related_list_jlt6k__c",
        "field_num": 346,
        "target_related_list_label": "\u9500\u552e\u7ebf\u7d22",
        "action_on_target_delete": "cascade_delete",
        "is_need_convert": False,
        "is_required": False,
        "wheres": [],
        "api_name": "UDLookUp1__c",
        "define_type": "custom",
        "is_extend": True,
        "is_single": False,
        "is_index_field": False,
        "index_name": "s_18",
    },
    "department": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": False,
        "create_time": 1560750495089,
        "pattern": "",
        "description": "\u90e8\u95e8",
        "is_unique": False,
        "label": "\u90e8\u95e8",
        "type": "text",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "department",
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 1,
            "enable": 1,
            "attrs": {"wheres": 1, "is_required": True, "label": 1, "help_text": 1},
        },
        "index_name": "t_4",
        "max_length": 100,
    },
    "UDMSel1__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495099,
        "description": "\u63a5\u5355\u7c7b\u578b",
        "is_unique": False,
        "label": "\u63a5\u5355\u7c7b\u578b",
        "type": "select_many",
        "field_num": 231,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDMSel1__c",
        "options": [
            {
                "label": "\u6574\u88c5",
                "value": "1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5c40\u88c5",
                "value": "2",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5de5\u88c5",
                "value": "3",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u8f6f\u88c5",
                "value": "4",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u522b\u5885",
                "value": "5",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "a_5",
        "config": {},
    },
    "UDSSel9__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495115,
        "description": "\u5173\u8054\u5fae\u4fe1",
        "is_unique": False,
        "label": "\u5173\u8054\u5fae\u4fe1",
        "type": "select_one",
        "field_num": 189,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDSSel9__c",
        "options": [
            {
                "label": "\u8003\u8651\u4e2d\uff0c\u8fd8\u4e0d\u613f\u52a0\u5fae\u4fe1",
                "value": "1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5df2\u4e92\u52a0\u5fae\u4fe1",
                "value": "2",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "s_27",
        "config": {},
    },
    "email": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": False,
        "create_time": 1560750495115,
        "pattern": "\\w+((-w+)|(\\.\\w+))*\\@[A-Za-z0-9]+((\\.|-)[A-Za-z0-9]+)*\\.[A-Za-z0-9]+",
        "description": "\u90ae\u4ef6",
        "is_unique": False,
        "label": "\u90ae\u4ef6",
        "type": "email",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "email",
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 1,
            "enable": 1,
            "attrs": {"wheres": 1, "is_required": True, "label": 1, "help_text": 1},
        },
        "index_name": "w_1",
    },
    "is_overtime": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495124,
        "description": "\u662f\u5426\u8d85\u65f6",
        "is_unique": False,
        "default_value": False,
        "label": "\u662f\u5426\u8d85\u65f6",
        "type": "True_or_False",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "is_overtime",
        "options": [
            {"label": "\u672a\u8d85\u65f6", "value": False},
            {"label": "\u5df2\u8d85\u65f6", "value": True},
        ],
        "define_type": "system",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 0,
            "display": 1,
            "attrs": {"wheres": 1, "is_required": True, "label": 1, "help_text": 1},
        },
        "index_name": "b_1",
    },
    "UDSSel5__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": False,
        "create_time": 1560750495139,
        "description": "\u662f\u5426\u6709\u5165\u9a7b\u4fe1\u606f",
        "is_unique": False,
        "label": "\u662f\u5426\u6709\u5165\u9a7b\u4fe1\u606f",
        "type": "select_one",
        "field_num": 185,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDSSel5__c",
        "options": [
            {
                "label": "\u662f",
                "value": "1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5426",
                "value": "2",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "s_23",
        "config": {},
    },
    "owner": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495139,
        "length": 18,
        "description": "\u8d1f\u8d23\u4eba",
        "is_unique": False,
        "label": "\u8d1f\u8d23\u4eba",
        "type": "employee",
        "decimal_places": 0,
        "is_need_convert": True,
        "is_required": False,
        "api_name": "owner",
        "define_type": "system",
        "is_index_field": False,
        "is_single": True,
        "config": {
            "edit": 0,
            "display": 1,
            "attrs": {"wheres": 1, "label": 1, "help_text": 1},
        },
        "index_name": "owner",
        "round_mode": 4,
    },
    "picture_path": {
        "describe_api_name": "LeadsObj",
        "file_amount_limit": 20,
        "is_index": False,
        "is_active": True,
        "create_time": 1560750495139,
        "description": "\u540d\u7247",
        "is_unique": False,
        "label": "\u540d\u7247",
        "type": "image",
        "is_watermark": False,
        "file_size_limit": 10485760,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "picture_path",
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 1,
            "enable": 1,
            "attrs": {
                "file_amount_limit": 1,
                "wheres": 1,
                "is_required": True,
                "options": 1,
                "label": 1,
                "is_watermark": 1,
                "help_text": 1,
            },
        },
        "index_name": "a_4",
        "support_file_types": [],
    },
    "address": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": False,
        "create_time": 1560750495139,
        "pattern": "",
        "description": "\u5730\u5740",
        "is_unique": False,
        "label": "\u5730\u5740",
        "type": "text",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "address",
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 1,
            "enable": 1,
            "attrs": {"wheres": 1, "is_required": True, "label": 1, "help_text": 1},
        },
        "index_name": "t_1",
        "max_length": 400,
    },
    "UDMText1__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495139,
        "pattern": "",
        "description": "\u8ddf\u8fdb\u5907\u6ce8",
        "is_unique": False,
        "label": "\u8ddf\u8fdb\u5907\u6ce8",
        "type": "long_text",
        "field_num": 51,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDMText1__c",
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "t_9",
        "max_length": 2000,
    },
    "last_modified_time": {
        "is_index": True,
        "create_time": 1530510400372,
        "is_unique": False,
        "description": "last_modified_time",
        "label": "\u6700\u540e\u4fee\u6539\u65f6\u95f4",
        "type": "date_time",
        "time_zone": "",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "last_modified_time",
        "define_type": "system",
        "date_format": "yyyy-MM-dd HH:mm:ss",
        "index_name": "md_time",
    },
    "completed_result": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495139,
        "pattern": "",
        "description": "\u5904\u7406\u7ed3\u679c",
        "is_unique": False,
        "label": "\u5904\u7406\u7ed3\u679c",
        "type": "long_text",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "completed_result",
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 0,
            "display": 1,
            "attrs": {"wheres": 1, "is_required": True, "label": 1, "help_text": 1},
        },
        "index_name": "t_3",
        "max_length": 1000,
    },
    "UDSText6__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495139,
        "pattern": "",
        "description": "\u516c\u53f8\u4e3b\u8425\u4e1a\u52a1",
        "is_unique": False,
        "label": "\u516c\u53f8\u4e3b\u8425\u4e1a\u52a1",
        "type": "text",
        "field_num": 6,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDSText6__c",
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "t_14",
        "max_length": 100,
    },
    "life_status": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1561215074917,
        "description": "\u751f\u547d\u72b6\u6001",
        "is_unique": False,
        "default_value": "normal",
        "label": "\u751f\u547d\u72b6\u6001",
        "type": "select_one",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "life_status",
        "options": [
            {
                "label": "\u672a\u751f\u6548",
                "value": "ineffective",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u5ba1\u6838\u4e2d",
                "value": "under_review",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6b63\u5e38",
                "value": "normal",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u53d8\u66f4\u4e2d",
                "value": "in_change",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u4f5c\u5e9f",
                "value": "invalid",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "system",
        "is_index_field": False,
        "is_single": False,
        "config": {"edit": 0, "display": 1, "attrs": {"wheres": 1, "help_text": 1}},
        "index_name": "s_8",
    },
    "mobile": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495139,
        "pattern": "^[0-9+\\-;,]{0,100}$",
        "description": "\u624b\u673a",
        "is_unique": False,
        "label": "\u624b\u673a",
        "type": "phone_number",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "mobile",
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 1,
            "enable": 1,
            "attrs": {"wheres": 1, "is_required": True, "label": 1, "help_text": 1},
        },
        "index_name": "p_1",
    },
    "last_modified_by": {
        "is_index": True,
        "is_active": True,
        "create_time": 1530510400372,
        "is_unique": False,
        "label": "\u6700\u540e\u4fee\u6539\u4eba",
        "type": "employee",
        "is_need_convert": True,
        "is_required": False,
        "api_name": "last_modified_by",
        "define_type": "system",
        "is_single": True,
        "index_name": "md_by",
    },
    "out_tenant_id": {
        "is_index": False,
        "create_time": 1530510400372,
        "pattern": "",
        "is_unique": False,
        "description": "out_tenant_id",
        "label": "\u5916\u90e8\u4f01\u4e1a",
        "type": "text",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "out_tenant_id",
        "define_type": "system",
        "index_name": "o_ei",
        "config": {"display": 0},
        "max_length": 200,
    },
    "record_type": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495151,
        "description": "record_type",
        "is_unique": False,
        "label": "\u4e1a\u52a1\u7c7b\u578b",
        "type": "record_type",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "record_type",
        "options": [
            {
                "is_active": True,
                "api_name": "default__c",
                "description": "\u9884\u8bbe\u4e1a\u52a1\u7c7b\u578b",
                "label": "\u9884\u8bbe\u4e1a\u52a1\u7c7b\u578b",
            }
        ],
        "define_type": "system",
        "is_extend": False,
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 0,
            "enable": 0,
            "display": 1,
            "attrs": {"wheres": 1, "help_text": 1},
        },
        "index_name": "r_type",
        "help_text": "",
    },
    "url": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": False,
        "create_time": 1560750495139,
        "pattern": "",
        "description": "\u7f51\u5740",
        "is_unique": False,
        "label": "\u7f51\u5740",
        "type": "text",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "url",
        "define_type": "package",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "edit": 1,
            "enable": 1,
            "attrs": {"wheres": 1, "is_required": True, "label": 1, "help_text": 1},
        },
        "index_name": "t_16",
        "max_length": 1000,
    },
    "marketing_event_id": {
        "describe_api_name": "LeadsObj",
        "default_is_expression": False,
        "is_index": True,
        "is_active": False,
        "create_time": 1560750495151,
        "description": "\u5e02\u573a\u6d3b\u52a8\u540d\u79f0",
        "is_unique": False,
        "label": "\u5e02\u573a\u6d3b\u52a8\u540d\u79f0",
        "target_api_name": "MarketingEventObj",
        "type": "object_reference",
        "target_related_list_name": "marketing_event_leads_list",
        "target_related_list_label": "\u9500\u552e\u7ebf\u7d22",
        "action_on_target_delete": "cascade_delete",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "marketing_event_id",
        "define_type": "package",
        "is_single": False,
        "is_index_field": False,
        "index_name": "s_11",
        "config": {
            "edit": 1,
            "enable": 1,
            "attrs": {"wheres": 1, "is_required": True, "label": 1, "help_text": 1},
        },
    },
    "account_id": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495151,
        "description": "\u5ba2\u6237\u540d\u79f0",
        "is_unique": False,
        "label": "\u5ba2\u6237\u540d\u79f0",
        "target_api_name": "AccountObj",
        "type": "object_reference",
        "target_related_list_name": "account_leads_list",
        "target_related_list_label": "\u9500\u552e\u7ebf\u7d22",
        "action_on_target_delete": "cascade_delete",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "account_id",
        "define_type": "system",
        "is_index_field": False,
        "is_single": False,
        "config": {"display": 0},
        "index_name": "s_1",
    },
    "returned_time": {
        "describe_api_name": "LeadsObj",
        "is_index": False,
        "is_active": True,
        "create_time": 1566478398173,
        "description": "returned_time",
        "is_unique": False,
        "label": "\u9000\u56de/\u6536\u56de\u65f6\u95f4",
        "time_zone": "GMT+8",
        "type": "date_time",
        "is_need_convert": False,
        "is_required": False,
        "api_name": "returned_time",
        "define_type": "package",
        "date_format": "yyyy-MM-dd HH:mm:ss",
        "is_index_field": False,
        "is_single": False,
        "config": {
            "add": 0,
            "edit": 0,
            "enable": 0,
            "display": 1,
            "remove": 0,
            "attrs": {
                "wheres": 1,
                "is_required": 0,
                "default_value": 0,
                "help_text": 1,
            },
        },
    },
    "UDSText3__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": False,
        "create_time": 1560750495151,
        "pattern": "",
        "description": "\u4e1a\u52a1\u7ebf",
        "is_unique": False,
        "label": "\u4e1a\u52a1\u7ebf",
        "type": "text",
        "field_num": 3,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDSText3__c",
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "t_11",
        "max_length": 100,
    },
    "UDSSel8__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495156,
        "description": "\u6709\u6548\u8ddf\u8fdb\u7ed3\u679c",
        "is_unique": False,
        "label": "\u6709\u6548\u8ddf\u8fdb\u7ed3\u679c",
        "type": "select_one",
        "field_num": 188,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDSSel8__c",
        "options": [
            {
                "label": "\u88c5\u4fee\u516c\u53f8\u60f3\u5408\u4f5c",
                "value": "1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u9080\u7ea6\u6210\u529f",
                "value": "2",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u518d\u8054\u7cfb",
                "value": "3",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u6709\u610f\u5411\u6301\u7eed\u8ddf\u8fdb",
                "value": "4",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u975e\u51b3\u7b56\u4eba",
                "value": "5",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "s_26",
        "config": {},
    },
    "UDSSel4__c": {
        "describe_api_name": "LeadsObj",
        "is_index": True,
        "is_active": True,
        "create_time": 1560750495164,
        "description": "\u8ddf\u8fdb\u7ebf\u7d22\u6807\u8bc6",
        "is_unique": False,
        "label": "\u8ddf\u8fdb\u7ebf\u7d22\u6807\u8bc6",
        "type": "select_one",
        "field_num": 184,
        "is_need_convert": False,
        "is_required": False,
        "api_name": "UDSSel4__c",
        "options": [
            {
                "label": "\u6709\u6548",
                "value": "1",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
            {
                "label": "\u65e0\u6548",
                "value": "2",
                "config": {"edit": 1, "enable": 1, "remove": 1},
            },
        ],
        "define_type": "custom",
        "is_extend": True,
        "is_index_field": False,
        "is_single": False,
        "index_name": "s_22",
        "config": {},
    },
}

s = {
    "account_id",
    "address",
    "assigned_time",
    "assigner_id",
    "back_reason",
    "close_reason",
    "company",
    "completed_result",
    "contact_id",
    "department",
    "email",
    "is_overtime",
    "job_title",
    "last_follower",
    "last_follow_time",
    "leads_pool_id",
    "leads_status",
    "lock_status",
    "marketing_event_id",
    "mobile",
    "name",
    "new_opportunity_id",
    "opportunity_id",
    "out_resources",
    "owner",
    "owner_change_time",
    "owner_department",
    "partner_id",
    "picture_path",
    "record_type",
    "remark",
    "source",
    "tel",
    "transform_time",
    "UDDate1__c",
    "UDDate2__c",
    "UDLookUp1__c",
    "UDMSel1__c",
    "UDMSel2__c",
    "UDMSel3__c",
    "UDMText1__c",
    "UDSSel1__c",
    "UDSSel2__c",
    "UDSSel3__c",
    "UDSSel4__c",
    "UDSSel5__c",
    "UDSSel6__c",
    "UDSSel7__c",
    "UDSText1__c",
    "UDSText3__c",
    "UDSText4__c",
    "UDSText5__c",
    "UDSText6__c",
    "UDSText9__c",
    "url",
    "index_id",
    "created_by",
    "last_modified_by",
    "create_time",
    "last_modified_time",
    "is_deleted",
    "out_tenant_id",
    "out_owner",
    "relevant_team",
    "UDSSel8__c",
    "UDSSel9__c",
    "data_own_department",
    "extend_obj_data_id",
}

for (
    field,
    _tmp_dict,
) in sorted(d.items(), key=lambda asd: asd[0]):
    if field not in s:
        print(field)
        # print(field, tmp_dict["label"])
