[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "colourspace"
version = "1.0.1"
description = "Render frames from videos and images applying the correct colourspace conversion."
readme = "README.md"
authors = [{ name = "Svetlin Ankov", email = "svetlin.ankov@live.com" }, { name = "Simona Dimitrova", email = "nimeria1308@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Intended Audience :: Science/Research",
    "Topic :: Desktop Environment",
    "Topic :: Multimedia :: Video :: Display",
    "Topic :: Scientific/Engineering :: Image Processing",
]
keywords = ["colourspace", "colorspace", "video", "render"]
dependencies = [
    "av >= 10.0.0",
    "pymediainfo >= 6.0.1",
    "wxPython >= 4.2.0",
    "Pillow >= 9.0.1",
    "pylru >= 1.2.1",
]
requires-python = ">=3.9"

[project.optional-dependencies]
dev = ["autopep8", "pytest"]

[project.urls]
Homepage = "https://github.com/dumbledore/colourspace"

[project.scripts]
colourview = "colourspace.frontend.viewer.app:main"
