
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-08T13:47:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a38cbf9a74d1df47a690811902782559d106c5f0",
 "version": "0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
