# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev8+g1499dec.d20230811'
__version_tuple__ = version_tuple = (0, 1, 'dev8', 'g1499dec.d20230811')
