BASE_URL = "https://api.deps.dev/v3alpha"
SUPPORTED_SYSTEMS = ["GO", "NPM", "CARGO", "MAVEN", "PYPI"]
SUPPORTED_HASHES = ["MD5", "SHA1", "SHA256", "SHA512"]

DEFAULT_MAX_RETRIES = 3
DEFAULT_BASE_BACKOFF = 1
DEFAULT_MAX_BACKOFF = 5
DEFAULT_TIMEOUT_DURATION = 20
