# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.3.dev0+g9d4ad39.d20230810'
__version_tuple__ = version_tuple = (0, 2, 3, 'dev0', 'g9d4ad39.d20230810')
