
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-11T11:20:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "36f8c141cb336d7b20d216bbdff6542cf67f9078",
 "version": "0.8.0.post.dev28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
