# Copyright (c) 2022 IO-Aero. All rights reserved. Use of this
# source code is governed by the IO-Aero License, that can
# be found in the LICENSE.md file.

"""Module stub file."""
import logging.config

# Environment types.
ENVIRONMENT_TYPE_DEV: str = ...
ENVIRONMENT_TYPE_PROD: str = ...
ENVIRONMENT_TYPE_TEST: str = ...

# Error messages.

FILE_ENCODING_DEFAULT = ...

INFO_00_001: str = ...
INFORMATION_NOT_YET_AVAILABLE: str = ...
IO_TEMPLATE_LIB_VERSION: str = ...

LOGGER_END: str = ...
LOGGER_NAME: str = ...
LOGGER_START: str = ...

logger: logging.Logger
