
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-08T14:11:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d59a960f89873667d6190489ff0e975091e57d10",
 "version": "5.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
