
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-13T13:35:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "39f4ad3584ec9a6ea4efe4347712e75d0fcb7ef3",
 "version": "1.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
