
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-09T17:33:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7d5e9b313aea06b2e5a8dc94f9070a45cdc9ae7d",
 "version": "1.59.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
