
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-09T11:40:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e03d3819b69221a1d67e14a1609d5b3cf3ab253b",
 "version": "0.8.0.post.dev20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
