VERSION_YEAR = 2023
VERSION_MONTH = int('08')
VERSION_DAY = int('14')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('05')
MAJOR_VERSION = 0
MINOR_VERSION = 4
PATCH_VERSION = 202308141005
version_date = '2023/08/14 10:05'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
