from .content import ContentManager as ContentManager
from .naming import CharacterNamingMetaData as CharacterNamingMetaData
from .processor import Processor as Processor

class Compiler:
    def load(self, path: str) -> dict: ...
    @staticmethod
    def compile(path: str, out_folder: str) -> None: ...
    @classmethod
    def compile_files_in_directory(cls, _path: str) -> None: ...
    @classmethod
    def decompile(cls, _data: dict, out: str) -> None: ...
