from .content import Content as Content
from .exception import ScriptsProcessingException as ScriptsProcessingException
from .naming import CharacterNamingMetaData as CharacterNamingMetaData
from typing import Final

class Processor:
    SCRIPTS_FILE_EXTENSION: Final[str]
    def __init__(self) -> None: ...
    def get_output(self) -> dict: ...
    def process(self, _path: str) -> None: ...
    def save_to(self, out_folder: str) -> None: ...
