
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-08-10T13:44:56-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a70cddd6b91d7427e35738ed9af1bf8a1c91a3ef",
 "version": "0.18.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
