def help():
    from time import sleep
    print("Nesse Modulo existem os seguintes comandos: ")
    sleep(1)
    print("Fatorial --> Calcula O fatorial de um número Ex: fatorial(numero)")
    sleep(1)
    print("Dobro --> Calcula o dobro de um número Ex: dobro(numero)")
    sleep(1)
    print("Triplo --> Calcula o triplo do número Ex: triplo(numero)")
    sleep(1)
    print("Quatruplo --> Calcula o Quatruplo do número Ex: quatruplo(numero)")
    sleep(1)
    print("Media --> Calcula a media de um número Ex: media(numero)")
    sleep(1)
    print("Help --> Ajuda O usuario a saber os comandos no modulo Ex: help()")
    sleep(1)
    print("Aumentar --> Aumenta o número na porcentagem escolhida Ex: aumentar(numero,porcentagem)")
    sleep(1)
    print("Metade --> Retorna a metade do número escolhido Ex: metade(numero), metade(10) == 5")
    sleep(1)
    print("Linha --> Imprime uma linha com o caracter '=' com o tamanho escolhido Ex: linha(tamanho)")
    sleep(1)
    print("Diminuir --> Semelhante ao 'Aumentar' porem esse diminui o número na porcentagem escolhida Ex: diminuir(número,porcentagem)")
    sleep(1)
    print("Leiaint --> Força o usuario a digitar um número inteiro Ex: leiaint('digite um número:')")
    print("-=-=-=-=-=-=-=-=-=-")
    sleep(1)
    print("Espero ter ajudado!")
    sleep(1)
    print("-=-=-=-=-=-=-=-=-=-")
    sleep(1)