[build-system]
requires = ["setuptools>=61.0.0", "wheel", "setuptools_scm[toml]>=6.2", "numpy>=1.21.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nanolsap"
authors = [
    {name = "hzqmwne", email = "huangzhengqmwne@sina.cn"},
]
description = "Python module to solve the linear sum assignment problem (LSAP) low memory friendly"
readme = "README.md"
urls = {Homepage = "https://github.com/hzqmwne/nanolsap"}
requires-python = ">=3.7"
keywords = ["lsap", "munkres", "kuhn-munkres", "linear sum assignment problem"]
license = {text = "BSD-3-Clause"}
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
]
dependencies = [
    "numpy>=1.21.0",
    'importlib-metadata; python_version<"3.8"',
]
dynamic = ["version"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["py.typed"]

[tool.setuptools.exclude-package-data]
"*" = ["*.c", "*.cpp", "*.h"]

[tool.setuptools_scm]
write_to = "src/nanolsap/_version.py"

[tool.cibuildwheel]
build = "cp37-*"
skip = "*-musllinux*"
test-requires = ["pytest", "scipy"]
test-command = "pytest {project}/tests"

[tool.cibuildwheel.macos]
build = "cp38-*"
archs = ["universal2"]
