from _typeshed import Incomplete

class Content:
    background_image: Incomplete
    background_music: Incomplete
    character_images: Incomplete
    contents: Incomplete
    narrator: Incomplete
    previous: Incomplete
    next: Incomplete
    notes: Incomplete
    def __init__(self, _data: dict, _id: str) -> None: ...
    @property
    def id(self) -> str: ...
    def has_next(self) -> bool: ...
    def has_multiple_next(self) -> bool: ...
    def to_dict(self) -> dict: ...

class ContentManager:
    def __init__(self) -> None: ...
    @property
    def previous(self) -> Content | None: ...
    @property
    def current(self) -> Content: ...
    @property
    def last(self) -> Content | None: ...
    def save_current_changes(self) -> None: ...
    def is_empty(self) -> bool: ...
    def clear(self) -> None: ...
    def update(self, _data: dict[str, dict[str, dict]]) -> None: ...
    def get(self) -> dict[str, dict[str, dict]]: ...
    def get_id(self) -> str: ...
    def set_id(self, _id: str) -> None: ...
    def get_section(self) -> str: ...
    def set_section(self, _section: str) -> None: ...
    def remove_section(self, _id: str | None = ...) -> None: ...
    def get_section_content(self, _section: str | None = ...) -> dict: ...
    def set_section_content(self, _data: dict, _section: str | None = ...) -> None: ...
    def get_dialog(self, _section: str | None = ..., _id: str | None = ...) -> dict: ...
    def remove_dialog(self, _section: str | None = ..., _id: str | None = ...) -> None: ...
