class CharacterNamingMetaData:
    @classmethod
    def get_database(cls) -> dict: ...
    def __init__(self, _name: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def tags(self) -> set[str]: ...
    def equal(self, otherNameData: CharacterNamingMetaData, must_be_the_same: bool = ...) -> bool: ...
    def has_tag(self, _tag: str) -> bool: ...
    def remove_tag(self, _tag: str) -> None: ...
    def add_tag(self, _tag: str) -> None: ...
    def get_raw_name(self) -> str: ...
