# Generated by Django 4.0.4 on 2022-11-12 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
    ]
