# Generated by Django 4.0.4 on 2022-11-12 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221112_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mxpi_SArduino_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1000)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.RenameModel(
            old_name='MxpiArticles',
            new_name='Mxpi_SArduino_in',
        ),
    ]
