# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.0.0-beta.10

import enum

import toasts_winrt.system

_ns_module = toasts_winrt.system._import_ns_module("Windows.UI.Notifications.Management")

try:
    import toasts_winrt.windows.foundation
except ImportError:
    pass

try:
    import toasts_winrt.windows.foundation.collections
except ImportError:
    pass

try:
    import toasts_winrt.windows.ui.notifications
except ImportError:
    pass

class UserNotificationListenerAccessStatus(enum.IntEnum):
    UNSPECIFIED = 0
    ALLOWED = 1
    DENIED = 2

_ns_module._register_UserNotificationListenerAccessStatus(UserNotificationListenerAccessStatus)

UserNotificationListener = _ns_module.UserNotificationListener
